version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: <"host">
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: <"user">
      DB_MYSQL_PASSWORD: <"password">
      DB_MYSQL_NAME: <"name">
    volumes:
      - /home/pi/docker/nginx/data:/data
      - /home/pi/docker/nginx/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: <'password'>   #same as DB_MYSQL_PASSWORD
      MYSQL_DATABASE: <'name'>            #same as DB_MYSQL_NAME
      MYSQL_USER: <'user'>                #same as DB_MYSQL_USER
      MYSQL_PASSWORD: <'password'>        #same as DB_MYSQL_PASSWORD
    volumes:
      - /home/pi/docker/nginx/data/mysql:/var/lib/mysql
